using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Config;
using HarmonyLib;
using Sdk;
using UnityEngine;
using UnityEngine.UI;
using View.Main;
using View.Evt;
using StudentAgeDialogueSave.UI;
using StudentAgeDialogueSave.GameIntegration;

public static class RuntimeSettingsQA
{
    public static IEnumerator Run(DialogueCheckpointAdapter adapter,Action<bool,string> check,Func<Func<bool>,float,string,IEnumerator> until,string root)
    {
        var owner=AdvDialogueController.Active;
        owner.Preferences.TextSpeed.Value=30;owner.Preferences.ButtonVolume.Value=.8f;owner.Preferences.Watermark.Value=true;
        var global=AccessTools.Field(typeof(GlobalMgr),"model").GetValue(Singleton<GlobalMgr>.Ins);
        var seen=(List<int>)AccessTools.Field(global.GetType(),"historyTalks").GetValue(global);seen?.Remove(1900000041);seen?.Remove(1900000042);
        var talk=(NewTalkView)UIMgr.GetView<NewTalkView>();
        yield return until(()=>talk.talkState==TalkState.AnimEnd,20,"settings fixture ready");
        if(File.Exists(Path.Combine(root,"confirmation-resume.txt"))){yield return ConfirmationSettings(owner,adapter,check,until);yield return ConfirmationAndDialogue(owner,talk,check,root);yield break;}
        var openWatch=System.Diagnostics.Stopwatch.StartNew();
        UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});
        openWatch.Stop();
        yield return until(()=>AdvSettings.Active!=null,15,"custom settings opens on native settings lifecycle");
        var settings=AdvSettings.Active;
        yield return until(()=>AdvSettingsTransition.Active!=null,5,"opening uses diagonal slat transition");
        yield return new WaitForSecondsRealtime(.12f);
        yield return new WaitForEndOfFrame();
        var openingFrame=ScreenCapture.CaptureScreenshotAsTexture();
        yield return until(()=>AdvSettingsTransition.Active==null,5,"opening transition cleans up snapshot and input guard");
        File.WriteAllBytes(Path.Combine(root,"results/settings-opening-slats.png"),openingFrame.EncodeToPNG());UnityEngine.Object.Destroy(openingFrame);
        yield return Shot(root,"settings-game");
        var idleTab=Resources.FindObjectsOfTypeAll<Button>().Single(b=>b.name=="Settings.Tab1" && b.gameObject.activeInHierarchy);
        var idleSprite=((Image)idleTab.targetGraphic).sprite;
        check(idleTab.GetComponent<SettingsButtonInk>().Text is TMPro.TextMeshProUGUI,"top tabs use native live text rather than artwork");
        check(idleSprite.texture.name=="settings-source-controls.png","top tabs use original source atlas");
        check(idleTab.GetComponent<SettingsButtonInk>().Brush.enabled,"idle top tab displays white brush backing");
        var tabPointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current);
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        check(!idleTab.GetComponent<SettingsButtonInk>().Brush.enabled,"hover hides white brush backing");
        check(idleTab.spriteState.highlightedSprite!=idleSprite,"top tab swaps transparent idle to white hover");
        var ink=idleTab.GetComponent<SettingsButtonInk>();
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerDownHandler);
        var pressedColor=ink.Text.color;var pressedImage=((Image)idleTab.targetGraphic).overrideSprite;
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        check(ink.Text.color==pressedColor && ((Image)idleTab.targetGraphic).overrideSprite==pressedImage,"held pointer outside keeps pressed text and frame, no hover mixture");
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        check(ink.Text.color==pressedColor && !ink.Brush.enabled,"held pointer reenter keeps pressed state and hides brush");
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerUpHandler);
        yield return Shot(root,"settings-tab-hover");
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerDownHandler);
        check(!idleTab.GetComponent<SettingsButtonInk>().Brush.enabled,"pressed top tab hides brush backing");
        UnityEngine.EventSystems.ExecuteEvents.Execute(idleTab.gameObject,tabPointer,UnityEngine.EventSystems.ExecuteEvents.pointerUpHandler);
        check(!settings.GetComponentsInChildren<Button>().Single(b=>b.name=="Settings.Tab0").GetComponent<SettingsButtonInk>().Brush.enabled,"selected top tab has no brush backing");
        check(adapter.IsPausedForMenu,"settings pauses typing and native dialogue");
        check(!settings.GetComponentsInChildren<Transform>().Any(t=>t.name=="Source heading icon"),"heading list icons removed");
        check(!settings.GetComponentsInChildren<TMPro.TextMeshProUGUI>().Any(t=>t.text=="‹" || t.text=="›"),"all left right cycling buttons removed");
        int oldSpeed=Singleton<SettingCtrl>.Ins.txtSpeed;
        var speedChoices=settings.GetComponentsInChildren<Button>().Where(b=>b.transform.parent.name=="文本速度").ToArray();
        check(speedChoices.Length==4,"all native text speed choices are listed");
        speedChoices[(oldSpeed+1)%4].onClick.Invoke();
        check(Singleton<SettingCtrl>.Ins.txtSpeed==(oldSpeed+1)%4,"direct choice applies native text speed");
        RuntimeUiQA.Click("Settings.Tab2",check);
        yield return until(()=>AdvSettingsTransition.Active!=null,5,"top tab click starts page transition");
        check(AdvSettingsTransition.Active.GetComponentsInChildren<SettingsSlats>().All(s=>s.Horizontal),"tab content changes with horizontal blinds");
        yield return new WaitForSecondsRealtime(.12f);yield return new WaitForEndOfFrame();
        var pageFrame=ScreenCapture.CaptureScreenshotAsTexture();
        yield return until(()=>AdvSettingsTransition.Active==null,5,"tab transition releases snapshot and input guard");
        check(settings.Tab==2,"tab click reaches audio page");
        File.WriteAllBytes(Path.Combine(root,"results/settings-page-blinds.png"),pageFrame.EncodeToPNG());UnityEngine.Object.Destroy(pageFrame);
        var frost=settings.transform.Find("Settings.Tab0.Blurred interior");
        check(frost==null,"top tabs retain original border with no background blur layer");
        var native=(SettingView)UIMgr.GetView<SettingView>();float master=native.slider_volume_master.value;
        settings.ShowTab(1);yield return Shot(root,"settings-display");
        settings.ShowTab(2);yield return Shot(root,"settings-audio");
        Slider("主音量").value=master>50?30:70;check(native.slider_volume_master.value!=master,"custom volume slider drives native mixer control");
        settings.ShowTab(3);yield return Shot(root,"settings-confirmations");
        check(settings.GetComponentsInChildren<Button>().Count(b=>b.name.StartsWith("Settings.Confirm.") && !b.name.Contains("All"))==ConfirmationOptions.Items.Length*2,"every confirmation group has ON/OFF buttons");
        var tabRects=settings.GetComponentsInChildren<Button>().Where(b=>b.name.StartsWith("Settings.Tab")).Select(b=>(RectTransform)b.transform).OrderBy(r=>r.anchoredPosition.x).ToArray();
        check(tabRects.Length==4 && tabRects.All(r=>Mathf.Abs(r.sizeDelta.x-tabRects[0].sizeDelta.x)<.1f) && Mathf.Abs(tabRects[3].anchoredPosition.x+tabRects[3].sizeDelta.x-tabRects[0].anchoredPosition.x-1176)<.1f,"four equal tabs retain previous total width");
        check(Mathf.Abs((tabRects[1].anchoredPosition.x-tabRects[0].anchoredPosition.x)-(tabRects[3].anchoredPosition.x-tabRects[2].anchoredPosition.x))<.1f,"tab gaps are equal");
        settings.ShowTab(0);settings.GetComponentsInChildren<ScrollRect>().First().verticalNormalizedPosition=0;yield return Shot(root,"settings-mod");
        var help=settings.GetComponentInChildren<AdvSettingsHelp>(true);
        check(settings.GetComponentsInChildren<Selectable>(true).All(b=>b.GetComponent<SettingsHelpTarget>()!=null && !string.IsNullOrEmpty(b.GetComponent<SettingsHelpTarget>().Description)),"every settings button and slider has explanatory help");
        var helpTab=settings.GetComponentsInChildren<Button>().Single(b=>b.name=="Settings.Tab2");
        var helpSlider=settings.GetComponentsInChildren<Slider>().Single(b=>b.name=="Settings.Slider.TextSpeed");
        var helpPointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current);
        UnityEngine.EventSystems.ExecuteEvents.Execute(helpTab.gameObject,helpPointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        yield return new WaitForSecondsRealtime(.08f);
        check(help.Opacity>0 && help.Opacity<1,"footer help fades in rather than appearing instantly");
        yield return new WaitForSecondsRealtime(.15f);
        check(help.Opacity==1 && help.Caption.Contains("主音量"),"top tab shows its own explanation");
        yield return Shot(root,"settings-help-top");
        UnityEngine.EventSystems.ExecuteEvents.Execute(helpSlider.gameObject,helpPointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        UnityEngine.EventSystems.ExecuteEvents.Execute(helpTab.gameObject,helpPointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        check(help.Caption.Contains("每秒显示"),"moving between controls updates help without stale pointer exit hiding it");
        yield return Shot(root,"settings-help-slider");
        UnityEngine.EventSystems.ExecuteEvents.Execute(helpSlider.gameObject,helpPointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        yield return new WaitForSecondsRealtime(.08f);
        check(help.Opacity>0 && help.Opacity<1,"footer help fades out after pointer leaves");
        yield return new WaitForSecondsRealtime(.15f);
        check(help.Opacity==0 && !help.GetComponent<CanvasGroup>().blocksRaycasts,"hidden help does not block input");
        var choiceButtons=settings.GetComponentsInChildren<Button>().Where(b=>b.transform.parent.name=="左下角学生时代水印").ToArray();
        var choicePointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current);
        UnityEngine.EventSystems.ExecuteEvents.Execute(choiceButtons[0].gameObject,choicePointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        check(choiceButtons[0].GetComponent<SettingsButtonInk>().Text.color==Color.white,"unselected choice hover inverts text to white");
        yield return Shot(root,"settings-choice-hover");
        UnityEngine.EventSystems.ExecuteEvents.Execute(choiceButtons[0].gameObject,choicePointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        var selectedInk=choiceButtons[1].GetComponent<SettingsButtonInk>().Text.color;
        UnityEngine.EventSystems.ExecuteEvents.Execute(choiceButtons[1].gameObject,choicePointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        check(choiceButtons[1].GetComponent<SettingsButtonInk>().Text.color==selectedInk,"selected choice hover retains text color");
        yield return Shot(root,"settings-choice-selected-hover");
        UnityEngine.EventSystems.ExecuteEvents.Execute(choiceButtons[1].gameObject,choicePointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        int built=settings.BuiltPages;
        var tabWatch=System.Diagnostics.Stopwatch.StartNew();
        for(int i=0;i<20;i++){settings.ShowTab(i%4);}
        settings.ShowTab(0);tabWatch.Stop();
        check(settings.BuiltPages==built,"repeated tabs reuse pages without rebuilding controls");
        if(File.Exists(Path.Combine(root,"settings-visual.txt")))
        {
            var range=Slider("ButtonVolume");range.value=62.375f;
            check(Mathf.Abs(range.value-62.375f)<.001f,"slider retains fractional movement without integer snapping");
            Canvas.ForceUpdateCanvases();var corners=new Vector3[4];((RectTransform)range.transform).GetWorldCorners(corners);
            check(Mathf.Abs(Mathf.Lerp(corners[0].x,corners[2].x,range.normalizedValue)-range.handleRect.position.x)<.5f,"paper plane position matches value on continuous gradient rail");
            range.OnPointerEnter(new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current));
            yield return Shot(root,"settings-slider-hover");
            var button=Resources.FindObjectsOfTypeAll<Button>().Single(b=>b.name=="Settings.Apply" && b.gameObject.activeInHierarchy);
            int clicks=AdvSkin.PlayedClicks;
            var pointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current){button=UnityEngine.EventSystems.PointerEventData.InputButton.Left};
            UnityEngine.EventSystems.ExecuteEvents.Execute(button.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
            check(button.GetComponent<SettingsButtonInk>().Text.color.b>.7f,"artwork caption changes blue on hover");
            yield return Shot(root,"settings-button-hover");
            UnityEngine.EventSystems.ExecuteEvents.Execute(button.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerDownHandler);
            check(button.GetComponent<SettingsButtonInk>().Text.color==Color.white,"artwork caption turns white when pressed");
            yield return Shot(root,"settings-button-pressed");
            UnityEngine.EventSystems.ExecuteEvents.Execute(button.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerUpHandler);
            RuntimeUiQA.Click("Settings.Cancel",check);
            yield return until(()=>AdvSettingsTransition.Active!=null,5,"closing uses reversed diagonal slats");
            yield return new WaitForSecondsRealtime(.12f);yield return new WaitForEndOfFrame();
            var closingFrame=ScreenCapture.CaptureScreenshotAsTexture();
            yield return until(()=>AdvSettings.Active==null && AdvSettingsTransition.Active==null,10,"visual preview closes cleanly");
            File.WriteAllBytes(Path.Combine(root,"results/settings-closing-slats.png"),closingFrame.EncodeToPNG());UnityEngine.Object.Destroy(closingFrame);
            check(AdvSkin.PlayedClicks==clicks+1,"settings button dispatches one click sound on native UI channel");
            check(Singleton<SettingCtrl>.Ins.txtSpeed==oldSpeed,"cancel restores direct native selection");
            var previous=settings;openWatch.Restart();
            UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});openWatch.Stop();
            yield return until(()=>AdvSettingsTransition.Active!=null,5,"cached settings starts opening transition");
            yield return until(()=>AdvSettings.Active!=null && AdvSettingsTransition.Active==null && !(bool)AccessTools.Field(typeof(AdvSettings),"transitionBusy").GetValue(AdvSettings.Active),10,"cached settings reopens");
            settings=AdvSettings.Active;
            check(settings==previous && settings.BuiltPages==built,"reopen reuses complete settings hierarchy");
            settings.ShowTab(0);settings.GetComponentsInChildren<ScrollRect>().First().verticalNormalizedPosition=0;yield return null;yield return null;float before=owner.Preferences.TextSpeed.Value;
            Slider("TextSpeed").value=42;Slider("AutoSpeed").value=85;Slider("ButtonVolume").value=23;
            RuntimeUiQA.Click("Settings.Choice.隐藏",check);
            RuntimeUiQA.Click("Settings.Defaults",check);yield return null;
            check(AdvConfirmation.IsOpen,"restore defaults opens campus confirmation");
            yield return Shot(root,"settings-restore-confirmation");
            RuntimeUiQA.Click("ADV.恢复默认Cancel",check);yield return until(()=>!AdvConfirmation.IsOpen && AdvSettingsTransition.Active==null,10,"default cancellation animation finishes");
            check(Slider("TextSpeed").value==42 && Slider("ButtonVolume").value==23,"cancel defaults preserves the draft");
            RuntimeUiQA.Click("Settings.Defaults",check);yield return null;
            RuntimeUiQA.Click("ADV.恢复默认Confirm",check);yield return until(()=>!AdvConfirmation.IsOpen && AdvSettingsTransition.Active==null,10,"defaults apply animation finishes");
            check(Slider("TextSpeed").value==30 && Slider("AutoSpeed").value==49 && Slider("ButtonVolume").value==80,"restore defaults matches screenshot numeric defaults");
            check(!(bool)AccessTools.Field(typeof(AdvSettings),"unread").GetValue(settings) && (bool)AccessTools.Field(typeof(AdvSettings),"watermark").GetValue(settings) && (string)AccessTools.Field(typeof(AdvSettings),"mode").GetValue(settings)=="ADV","restore defaults matches screenshot toggle defaults");
            check(help.GetComponent<RectTransform>().sizeDelta.x==770 && settings.transform.Find("Settings.Defaults")!=null,"shorter footer help leaves room for defaults button");
            var footerNames=new[]{"Settings.Defaults","Settings.Cancel","Settings.Apply"};
            var footer=footerNames.Select(n=>settings.GetComponentsInChildren<Button>().Single(b=>b.name==n)).ToArray();
            var rects=footer.Select(b=>b.GetComponent<RectTransform>()).ToArray();
            check(rects.All(r=>Mathf.Abs(r.sizeDelta.x-294)<.01f),"all three footer tickets have the same width");
            check(Mathf.Abs(rects[1].anchoredPosition.x-rects[0].anchoredPosition.x-rects[0].sizeDelta.x-40)<.01f && Mathf.Abs(rects[2].anchoredPosition.x-rects[1].anchoredPosition.x-rects[1].sizeDelta.x-40)<.01f,"footer tickets use equal 40px gaps");
            var helpRect=settings.GetComponentInChildren<AdvSettingsHelp>(true).GetComponent<RectTransform>();
            check(helpRect.anchoredPosition.x+helpRect.sizeDelta.x+24<=rects[0].anchoredPosition.x,"help strip leaves at least 24px before first ticket");
            check(footer.All(b=>b.GetComponent<SettingsButtonInk>().Text is Image),"every settings footer ticket uses artwork lettering");
            yield return Shot(root,"settings-restored-defaults");
            RuntimeUiQA.Click("Settings.Apply",check);
            yield return until(()=>AdvSettings.Active==null && AdvSettingsTransition.Active==null,10,"cached apply closes and releases transition");
            check(owner.Preferences.TextSpeed.Value==30 && owner.Preferences.AutoSpeed.Value==49 && !owner.Preferences.SkipUnread.Value && !adapter.IsPausedForMenu,"default apply persists and releases menu pause");
            owner.Preferences.TextSpeed.Value=before;owner.ApplyPreferences();
            yield return ConfirmationSettings(owner,adapter,check,until);
            yield return ConfirmationAndDialogue(owner,talk,check,root);
            File.WriteAllText(Path.Combine(root,"results/settings-performance.txt"),"warm_open_ms="+openWatch.Elapsed.TotalMilliseconds+"; cached_21_tabs_ms="+tabWatch.Elapsed.TotalMilliseconds+"; built_pages="+built);
            File.WriteAllText(Path.Combine(root,"results/settings-visual-success.txt"),"SLATS_SOURCE_BUTTON_STATES_CACHED_PAGES_CANCEL_APPLY_SOUND_OK");yield break;
        }
        float initialSpeed=owner.Preferences.TextSpeed.Value;
        Slider("TextSpeed").value=12;Slider("AutoSpeed").value=95;
        yield return new WaitForSecondsRealtime(.35f);
        var preview=Resources.FindObjectsOfTypeAll<TMPro.TextMeshProUGUI>().First(t=>t.gameObject.activeInHierarchy && t.text.StartsWith("放学后的风"));
        check(preview.maxVisibleCharacters>0 && preview.maxVisibleCharacters<preview.text.Length,"live text preview reveals progressively");
        RuntimeUiQA.Click("Settings.Cancel",check);
        yield return until(()=>AdvSettings.Active==null,10,"cancel closes overlay");
        check(Mathf.Abs(AudioMgr.Ins.GetVolume("MasterMixer")-master)<.1f,"cancel restores native mixer");
        check(owner.Preferences.TextSpeed.Value==initialSpeed && !adapter.IsPausedForMenu,"cancel discards mod drafts and releases pause");
        UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});
        yield return until(()=>AdvSettings.Active!=null,10,"settings reopens without duplicate overlay");
        settings=AdvSettings.Active;yield return new WaitForSecondsRealtime(.45f);settings.ShowTab(0);yield return null;yield return null;
        Slider("TextSpeed").value=42;Slider("ButtonVolume").value=35;
        RuntimeUiQA.Click("Settings.Choice.隐藏",check);yield return null;
        RuntimeUiQA.Click("Settings.Apply",check);yield return until(()=>AdvSettings.Active==null,10,"apply returns to dialogue");
        check(owner.Preferences.TextSpeed.Value==42 && Mathf.Abs(AdvSkin.ButtonVolume-.35f)<.01f && !owner.Preferences.Watermark.Value,"mod preferences applied and persisted");
        yield return null;yield return null;
        check(Resources.FindObjectsOfTypeAll<RawImage>().Where(i=>i.name=="ADV.StudentAgeLogo").All(i=>!i.gameObject.activeInHierarchy),"watermark toggle hides actual dialogue logo");
        // Exercise the native skip loop against an unread node and an interior node.
        var first=Cfg.TalkCfgMap[1900000001];var oldNext=first.nextTalk;
        first.nextTalk=new List<int>{1900000041};
        Cfg.TalkCfgMap[1900000041]=new TalkCfg{id=1900000041,bg=first.bg,roleIds=first.roleIds,content="这是尚未读过的新对白。仅跳过已读时应停在这里，让玩家完整阅读，再由玩家决定下一步。",nextTalk=new List<int>{1900000042}};
        Cfg.TalkCfgMap[1900000042]=new TalkCfg{id=1900000042,bg=first.bg,roleIds=first.roleIds,content="全部跳过时经过的中间对白也应成为已读。",nextTalk=new List<int>{1900000002}};
        Singleton<GlobalMgr>.Ins.AddTalkToHistory(first.id);owner.Preferences.SkipUnread.Value=false;
        AccessTools.Method(typeof(AdvDialogueController),"BeginSceneSkip").Invoke(owner,null);
        yield return until(()=>((TalkCfg)AccessTools.Field(typeof(NewTalkView),"cfg").GetValue(talk)).id==1900000041 && talk.talkState==TalkState.Anim,12,"read-only skip stops at first unread node");
        check(!Singleton<GlobalMgr>.Ins.HasSeenTalk(1900000041),"stopping before unread text does not mark it read");
        owner.Preferences.SkipUnread.Value=true;
        AccessTools.Method(typeof(AdvDialogueController),"BeginSceneSkip").Invoke(owner,null);
        yield return until(()=>talk.talkState==TalkState.Option,15,"skip-all stops at next actual choice");
        check(Singleton<GlobalMgr>.Ins.HasSeenTalk(1900000041) && Singleton<GlobalMgr>.Ins.HasSeenTalk(1900000042),"skipped current and interior unread nodes become native read history");
        check(Mathf.Abs(Time.timeScale-1)<.01f,"direct skipping never enables fast-forward time scale");
        first.nextTalk=oldNext;owner.Preferences.Watermark.Value=true;owner.Preferences.TextSpeed.Value=30;owner.Preferences.ButtonVolume.Value=.8f;owner.ApplyPreferences();
        File.WriteAllText(Path.Combine(root,"results/settings-success.txt"),"SETTINGS_NATIVE_CANCEL_APPLY_PREVIEWS_SKIP_READ_POLICY_OK");
    }
    static IEnumerator ConfirmationSettings(AdvDialogueController owner,DialogueCheckpointAdapter adapter,Action<bool,string> check,Func<Func<bool>,float,string,IEnumerator> until)
    {
        ConfirmationOptions.Apply(owner.Configuration,ConfirmationOptions.Items.ToDictionary(x=>x.Key,x=>true),true);
        UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});
        yield return until(()=>AdvSettings.Active!=null && AdvSettingsTransition.Active==null && !(bool)AccessTools.Field(typeof(AdvSettings),"transitionBusy").GetValue(AdvSettings.Active),10,"confirmation page opens for draft checks");
        AdvSettings.Active.ShowTab(3);yield return null;
        RuntimeUiQA.Click("Settings.Confirm.AllOff",check);yield return null;
        check(ConfirmationOptions.Snapshot(owner.Configuration).Values.All(v=>v),"all OFF remains draft before apply");
        RuntimeUiQA.Click("Settings.Cancel",check);
        yield return until(()=>AdvSettings.Active==null && AdvSettingsTransition.Active==null,10,"confirmation draft cancelled");
        check(ConfirmationOptions.Snapshot(owner.Configuration).Values.All(v=>v),"cancel discards all OFF");
        UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});
        yield return until(()=>AdvSettings.Active!=null && AdvSettingsTransition.Active==null && !(bool)AccessTools.Field(typeof(AdvSettings),"transitionBusy").GetValue(AdvSettings.Active),10,"confirmation settings reopened");
        AdvSettings.Active.ShowTab(3);yield return null;
        RuntimeUiQA.Click("Settings.Confirm.AllOff",check);yield return null;
        RuntimeUiQA.Click("Settings.Confirm.Load.On",check);yield return null;
        RuntimeUiQA.Click("Settings.Apply",check);
        yield return until(()=>AdvSettings.Active==null && AdvSettingsTransition.Active==null,10,"confirmation settings applied");
        owner.Configuration.Reload();
        check(ConfirmationOptions.Snapshot(owner.Configuration).All(p=>p.Value==(p.Key=="Load")),"all OFF plus individual ON persists to disk");
        UIMgr.OpenView<SettingView>(UILayerType.Tips,null,new object[]{true});
        yield return until(()=>AdvSettings.Active!=null && AdvSettingsTransition.Active==null && !(bool)AccessTools.Field(typeof(AdvSettings),"transitionBusy").GetValue(AdvSettings.Active),10,"confirmation settings reload");
        AdvSettings.Active.ShowTab(3);yield return null;
        RuntimeUiQA.Click("Settings.Confirm.AllOn",check);yield return null;
        RuntimeUiQA.Click("Settings.Apply",check);
        yield return until(()=>AdvSettings.Active==null && AdvSettingsTransition.Active==null,10,"all ON applied");
        owner.Configuration.Reload();
        check(ConfirmationOptions.Snapshot(owner.Configuration).Values.All(v=>v) && !adapter.IsPausedForMenu,"all ON persisted and menu pause released");
    }
    static IEnumerator ConfirmationAndDialogue(AdvDialogueController owner,NewTalkView talk,Action<bool,string> check,string root)
    {
        yield return null;yield return null;
        var text=(TMPro.TextMeshProUGUI)AccessTools.Field(typeof(AdvDialogueController),"shownText").GetValue(owner);
        var cfg=(TalkCfg)AccessTools.Field(typeof(NewTalkView),"cfg").GetValue(talk);
        var oldIds=cfg.roleIds;var oldName=cfg.roleName;
        cfg.roleIds=new List<int>{0};cfg.roleName="测试同学";
        AccessTools.Method(typeof(NewTalkView),"RefreshTalkingRole",new[]{typeof(List<int>),typeof(string)}).Invoke(talk,new object[]{cfg.roleIds,cfg.roleName});
        yield return null;
        text.ForceMeshUpdate(true,true);string raw=text.text;
        check(text.fontSharedMaterial.IsKeywordEnabled("UNDERLAY_ON") && text.fontSharedMaterial.GetFloat("_UnderlayOffsetY")<0,"dialogue has black offset shadow");
        check(text.font.faceInfo.familyName=="Microsoft YaHei","production dialogue uses Chinese patch Microsoft YaHei");
        var parsed=text.GetParsedText();
        File.WriteAllText(Path.Combine(root,"results/dialogue-presentation.txt"),"font="+text.font.faceInfo.familyName+"\nraw="+raw+"\nparsed="+parsed+"\nfull="+AccessTools.Field(typeof(AdvDialogueController),"fullLine").GetValue(owner));
        check(parsed.StartsWith("「") && parsed.EndsWith("」") && text.text==raw && !raw.StartsWith("「"),"dialogue brackets are presentation-only and preserve raw text");
        var speaker=(TMPro.TextMeshProUGUI)AccessTools.Field(typeof(AdvDialogueController),"nameLabel").GetValue(owner);
        check(speaker.text.StartsWith("【") && speaker.text.EndsWith("】"),"speaker is enclosed in corner brackets");
        yield return Shot(root,"dialogue-brackets-shadow");
        cfg.roleIds=oldIds;cfg.roleName=oldName;
        AccessTools.Method(typeof(NewTalkView),"RefreshTalkingRole",new[]{typeof(List<int>),typeof(string)}).Invoke(talk,new object[]{oldIds,oldName});
        RuntimeUiQA.Click("ADV.跳过剧情",check);yield return null;
        var remember=Resources.FindObjectsOfTypeAll<Button>().Single(b=>b.name=="ADV.SkipRemember" && b.gameObject.activeInHierarchy);
        var pointer=new UnityEngine.EventSystems.PointerEventData(UnityEngine.EventSystems.EventSystem.current);
        int hovers=AdvSkin.PlayedHovers,clicks=AdvSkin.PlayedClicks;
        UnityEngine.EventSystems.ExecuteEvents.Execute(remember.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerEnterHandler);
        check(AdvSkin.PlayedHovers==hovers+1,"confirmation checkbox hover plays original cursor sound once");
        check(remember.GetComponent<AdvConfirmToggle>().Label.color.b>.8f,"checkbox caption turns campus blue on hover");
        yield return Shot(root,"confirmation-checkbox-hover");
        RuntimeUiQA.Click("ADV.SkipRemember",check);yield return null;
        check(AdvSkin.PlayedClicks==clicks+1 && remember.GetComponent<AdvConfirmToggle>().Selected,"checkbox click plays original confirm sound once and selects");
        UnityEngine.EventSystems.ExecuteEvents.Execute(remember.gameObject,pointer,UnityEngine.EventSystems.ExecuteEvents.pointerExitHandler);
        check(remember.GetComponent<AdvConfirmToggle>().Icon.sprite.name!=null,"checkbox keeps selected dot on exit");
        yield return Shot(root,"confirmation-checkbox-selected");
        RuntimeUiQA.Click("ADV.SkipCancel",check);yield return new WaitForSecondsRealtime(.5f);
        check(!owner.ModalOpen,"cancel leaves native dialogue unchanged");
        owner.OpenHistory();yield return new WaitForSecondsRealtime(.55f);
        var back=Resources.FindObjectsOfTypeAll<Button>().Single(b=>b.name=="ADV.CloseHistory" && b.gameObject.activeInHierarchy);
        check(back.GetComponent<SettingsButtonInk>().Text is Image,"backlog return ticket uses artwork lettering");
        yield return Shot(root,"backlog-artwork-return");
        RuntimeUiQA.Click("ADV.CloseHistory",check);yield return null;
        File.WriteAllText(Path.Combine(root,"results/appearance-success.txt"),"DEFAULTS_BRACKETS_SHADOW_CONFIRMATION_SOURCE_SOUNDS_OK");
    }
    static Slider Slider(string name)=>Resources.FindObjectsOfTypeAll<Slider>().Single(s=>s.gameObject.activeInHierarchy && s.name=="Settings.Slider."+name);
    static IEnumerator Shot(string root,string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(root,"results",name+".png"));yield return new WaitForSecondsRealtime(.25f);}
}
